services:
  app:
    build:
      context: ./
      dockerfile: dev.Containerfile
    image: toppi_dev
    volumes:
      - ./:/opt/app-root/src
    ports:
      - 3000:3000
      - 8000:8000
    environment:
      DB_CONNECTION_STRING: postgres://toppi:toppi@db:5432/toppi
      JAMI_URL: https://api-toska.apps.ocp-test-0.k8s.it.helsinki.fi/jami
    container_name: toppi_dev
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: toppi
      POSTGRES_PASSWORD: toppi
      POSTGRES_DB: toppi
    ports:
      - 5432:5432
    container_name: toppi_db
    volumes:
      - toppi_dev_data:/data

volumes:
  toppi_dev_data:
