services:
  app:
    build:
      context: ./
      dockerfile: dev.Containerfile
    image: toppi_dev
    volumes:
      - ./:/opt/app-root/src
    ports:
      - 3000:3000
      - 8000:8000
    environment:
      DB_CONNECTION_STRING: postgres://toppi:toppi@db:5432/toppi
      JAMI_URL: http://jami:3003
    container_name: toppi_dev
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: toppi
      POSTGRES_PASSWORD: toppi
      POSTGRES_DB: toppi
    ports:
      - 5432:5432
    container_name: toppi_db

  jami:
    image: toska/jami:latest
    environment:
      - PORT=3003
      - NODE_ENV=dev
      - POSTGRES_HOST=jami-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - 3003:3003
    container_name: jami
  jami-db:
    image: postgres:15-alpine
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    container_name: jami-db
    ports:
      - 5433:5432
    volumes:
      - jami_data:/data

volumes:
  jami_data:
