version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Containerfile
      args:
        - E2E=true
    command: ['npm', 'run', 'start:test']
    ports:
      - 8000:8000
    container_name: toppi
